---
language: node_js
node_js:
  - "10"

sudo: false
dist: trusty

addons:
  apt:
    packages:
    - markdown

cache:
  directories:
    - $HOME/.npm
    - $HOME/uikit-build-cache

before_install:
  - npm config set spin false

script:
  - npm run build
  - markdown README.md > index.html
  - mv LICENSE README.md dist
  - (cd dist; zip --move --recurse-paths kursausschreibung.zip *)
  - mv index.html dist

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
